.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH MYCAT 1 "August 2009" Linux "User Manuals"
.SH NAME
mycat \- mycat my own version of cat
.SH SYNOPSIS
.B mycat [-l]
.I file
.B ...
.SH DESCRIPTION
.BR ‘mycat’ (1)
represents the first cat file as written by me.
.SH OPTIONS
.IP -l
display line number.
.I file
to display.
.SH FILES
.I file
.RS
Input file for display.
.RE
.SH ENVIRONMENT
.SH DIAGNOSTICS
Other dash options are non-support.
.SH BUGS
No known bugs. But use at your risk.
.SH AUTHOR
Fenchao Du
.SH "SEE ALSO"
