.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH MYLS 1 "August 2009" Linux "User Manuals"
.SH NAME
myls \- mycat my own version of cat
.SH SYNOPSIS
.B myls [-l]
.I file
.B ...
.SH DESCRIPTION
.BR ‘myls’ (1)
represents the first ls file as written by me.
.SH OPTIONS
.IP -l
display details for listed file.
.I file
to display.
.SH FILES
.I file
.RS
Input file for display.
.RE
.SH ENVIRONMENT
.SH DIAGNOSTICS
Other dash options are non-support.
.SH BUGS
No known bugs. But use at your risk.
.SH AUTHOR
Fenchao Du
.SH "SEE ALSO"
