.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH MYWC 1 "August 2009" Linux "User Manuals"
.SH NAME
mywc \- mycat my own version of cat
.SH SYNOPSIS
.B mywc [-l] [-w] [-m]
.I file
.B ...
.SH DESCRIPTION
.BR ‘mywc’ (1)
represents the first wc file as written by me.
.SH OPTIONS
.IP -l
display number of lines.
.IP -w
display number of words.
.IP -m
display number of chars.
.I file
to display.
.SH FILES
.I file
.RS
Input file for display.
.RE
.SH ENVIRONMENT
.SH DIAGNOSTICS
Other dash options are non-support.
.SH BUGS
No known bugs. But use at your risk.
.SH AUTHOR
Fenchao Du
.SH "SEE ALSO"
